////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated from a template.
////
////     Manual changes to this file may cause unexpected behavior in your application.
////     Manual changes to this file will be overwritten if the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace WebsiteHoaTuoi1080.Models
//{
//    using System;
//    using System.Collections.Generic;
//    using System.Linq;

//    public partial class Login
//    {
//        FlowerStoreEntities db = new FlowerStoreEntities();
//        public Login()
//        {
//            this.EMPLOYEES = new HashSet<EMPLOYEE>();
//        }

//        public int UserId { get; set; }
//        public string UserName { get; set; }
//        public string Password { get; set; }
//        public string Roles { get; set; }

//        public virtual ICollection<EMPLOYEE> EMPLOYEES { get; set; }

//        //0: login fail
//        //1: admin
//        //2: user

////////////////////////////////////////////////////////////////////
//Login.cs
        //public Login checkAccount(string userName, string password)
        //{
        //    Login tk = db.Logins.FirstOrDefault(l => l.UserName == userName && l.Password == password);
        //    if (tk != null)
        //    {
        //        return tk;
        //    }
        //    else return null;
        //}
//    }
//}

////////////////////////////////////////////////////////////////////
//Card.cs
        //public List<Card> getData(int maKH)
        //{
        //    return db.Cards.Where(c => c.CustomerID == maKH).ToList();
        //}

        //public void addItemCard(int maKH, int maSP, int soLuongMua = 1)
        //{
        //    List<Card> cards = db.Cards.Where(c => c.CustomerID == maKH).ToList();
        //    FlowerDetail fd = db.FlowerDetails.FirstOrDefault(f => f.FlowerID == maSP);
        //    if (cards == null)
        //    {
        //        Card item = new Card();

        //        item.CustomerID = maKH;
        //        item.FlowerID = fd.FlowerID;
        //        item.Path = fd.Path;
        //        item.FlowerName = fd.FlowerName;
        //        item.Quantity = soLuongMua;
        //        item.Price = fd.Price;
        //        item.SumPrice = item.Quantity * item.Price;

        //        db.Cards.Add(item);
        //    }
        //    else
        //    {
        //        Card item = cards.FirstOrDefault(f => f.FlowerID == fd.FlowerID);
        //        if (item == null)
        //        {
        //            item = new Card();

        //            item.CustomerID = maKH;
        //            item.FlowerID = fd.FlowerID;
        //            item.Path = fd.Path;
        //            item.FlowerName = fd.FlowerName;
        //            item.Quantity = soLuongMua;
        //            item.Price = fd.Price;
        //            item.SumPrice = item.Quantity * item.Price;

        //            db.Cards.Add(item);
        //        }
        //        else
        //        {
        //            item.Quantity += soLuongMua;
        //            item.SumPrice = item.Quantity * item.Price;
        //        }
        //    }
        //    db.SaveChanges();
        //}

        //public double sumTotalPrice(int maKH)
        //{
        //    double sumPrice = 0;
        //    List<Card> cards = db.Cards.Where(c => c.CustomerID == maKH).ToList();
        //    if (cards.Count > 0)
        //    {
        //        foreach (Card item in cards)
        //        {
        //            sumPrice += item.SumPrice;
        //        }
        //    }
        //    return sumPrice;
        //}

        //public void removeItemCard(int maKH, int maSP)
        //{
        //    Card card = db.Cards.FirstOrDefault(c => c.CustomerID == maKH && c.FlowerID == maSP);
        //    if (card != null)
        //    {
        //        db.Cards.Remove(card);
        //        db.SaveChanges();
        //    }
        //}

        //public void increasingTheNumber(int maKH, int maSP)
        //{
        //    Card card = db.Cards.FirstOrDefault(c => c.CustomerID == maKH && c.FlowerID == maSP);
        //    card.Quantity++;
        //    card.SumPrice = card.Quantity * card.Price;
        //    db.SaveChanges();
        //}

        //public void decreasingTheNumber(int maKH, int maSP)
        //{
        //    Card card = db.Cards.FirstOrDefault(c => c.CustomerID == maKH && c.FlowerID == maSP);
        //    if (card.Quantity > 1)
        //    {
        //        card.Quantity--;
        //        card.SumPrice = card.Quantity * card.Price;
        //        db.SaveChanges();
        //    }
        //}

        //public void confirmOrdererd(int maKH, Receiver_sInformation ri)
        //{
        //    //Tạo hoá đơn trước
        //    Ordererd or = createOrdererd(maKH, ri);
        //    db.Ordererds.Add(or);
        //    db.SaveChanges();

        //    //Tạo chi tiết hoá đơn
        //    int maHD = or.OrderID;
        //    createOrdersDetails(maKH, maHD);

        //    //Xoá thông tin giỏ hàng
        //    List<Card> cartsDelete = db.Cards.Where(c => c.CustomerID == maKH).ToList();
        //    db.Cards.RemoveRange(cartsDelete);
        //    db.SaveChanges();
        //}

        //public Ordererd createOrdererd(int maKH, Receiver_sInformation ri)
        //{
        //    //Tạo hoá đơn trước
        //    Ordererd or = new Ordererd();
        //    or.CustomerID = maKH;
        //    or.OrderDate = DateTime.Now;
        //    or.ReceiverName = ri.ReceiverName;
        //    or.ReceiverPhone = ri.ReceiverNumber;
        //    or.ReceiverAddress = ri.ReceiverAddress;
        //    or.TotalPrice = sumTotalPrice(maKH);

        //    return or;
        //}

        //public void createOrdersDetails(int maKH, int maHD)
        //{
        //    //Tạo hoá đơn trước
        //    List<Card> cards = db.Cards.Where(c => c.CustomerID == maKH).ToList();
        //    foreach (Card item in cards)
        //    {
        //        OrdersDetail ord = new OrdersDetail();
        //        ord.OrderID = maHD;
        //        ord.FlowerID = item.FlowerID;
        //        ord.Quantity = item.Quantity;
        //        ord.Price = item.Price;
        //        ord.SumPrice = item.SumPrice;
        //        db.OrdersDetails.Add(ord);
        //    }
        //    db.SaveChanges();
        //}  
