//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteHoaTuoi1080.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public CUSTOMER()
        {
            this.Cards = new HashSet<Card>();
            this.Ordererds = new HashSet<Ordererd>();
        }
    
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerNumber { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Login Login { get; set; }
        public virtual ICollection<Card> Cards { get; set; }
        public virtual ICollection<Ordererd> Ordererds { get; set; }
    }
}
