//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteHoaTuoi1080.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string Sex { get; set; }
        public string EmployeeAddress { get; set; }
        public string EmployeeNumber { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
