//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteHoaTuoi1080.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowerDetail
    {
        public FlowerDetail()
        {
            this.Cards = new HashSet<Card>();
        }
    
        public int FlowerID { get; set; }
        public string FlowerName { get; set; }
        public string Path { get; set; }
        public double Price { get; set; }
        public string Describe { get; set; }
        public string Ingredients { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Card> Cards { get; set; }
    }
}
