//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteHoaTuoi1080.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Login
    {
        FlowerStoreEntities db = new FlowerStoreEntities();
        public Login()
        {
            this.CUSTOMERs = new HashSet<CUSTOMER>();
            this.EMPLOYEES = new HashSet<EMPLOYEE>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Roles { get; set; }
    
        public virtual ICollection<CUSTOMER> CUSTOMERs { get; set; }
        public virtual ICollection<EMPLOYEE> EMPLOYEES { get; set; }

        public Login checkAccount(string userName, string password)
        {
            Login tk = db.Logins.FirstOrDefault(l => l.UserName == userName && l.Password == password);
            if (tk != null)
            {
                return tk;
            }
            else return null;
        }
    }
}
